host: khemenu.thoth-station.ninja
tls_verify: false
requirements_format: pip

runtime_environments:
  - name: rhel:8
    operating_system:
      name: rhel
      version: "8"
    python_version: "3.6"
    recommendation_type: stable